hump_0 = slim_run(humpy_script_0_image)
hump_2 = slim_run(humpy_script_2_image)
hump_10 = slim_run(humpy_script_10_image)

res_hump_0 = slim_results_to_data(hump_0)
res_hump_2 = slim_results_to_data(hump_2)
res_hump_10 = slim_results_to_data(hump_10)

png(filename = "~/humpy/first_0.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_0$data[[1]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "First genomes of individuals of the simulation (Nm=0)", outer = TRUE)
abline(v=50.5)
dev.off()

png(filename = "~/humpy/both_0.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_0$data[[2]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "both genomes of individuals of the simulation (Nm=0)", outer = TRUE)
abline(v=50.5)
dev.off()

png(filename = "~/humpy/first_2.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_2$data[[1]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "First genomes of individuals of the simulation (Nm=2)", outer = TRUE)
abline(v=50.5)
dev.off()

png(filename = "~/humpy/both_2.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_2$data[[2]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "both genomes of individuals of the simulation (Nm=2)", outer = TRUE)
abline(v=50.5)
dev.off()

png(filename = "~/humpy/first_10.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_10$data[[1]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "First genomes of individuals of the simulation (Nm=10)", outer = TRUE)
abline(v=50.5)
dev.off()

png(filename = "~/humpy/both_10.png")
par(oma =c(0,0,3,0))
par(mar= c(2,2,2,0.5))
plot.new()
ape::image.DNAbin(ape::as.DNAbin(res_hump_10$data[[2]]), c("a", "g", "c", "t"), legend = FALSE, show.labels = FALSE)
legend("bottom", inset = c(0,1), legend = c("A", "G", "C", "T"), col = c("red", "yellow", "green", "blue"), pch = c(15,15,15,15), horiz = TRUE, bty = "n", xpd = TRUE)
title(main = "both genomes of individuals of the simulation (Nm=10)", outer = TRUE)
abline(v=50.5)
dev.off()
